import { FoodCategory } from '../types/database';

export const MASTER_FOOD_CATEGORIES: FoodCategory[] = [
  { id: 'cat-burger', name: 'Burger', icon: '🍔', is_active: true, category_type: 'food' },
  { id: 'cat-biryani', name: 'Biryani', icon: '🍛', is_active: true, category_type: 'food' },
  { id: 'cat-pizza', name: 'Pizza', icon: '🍕', is_active: true, category_type: 'food' },
  { id: 'cat-chicken', name: 'Chicken', icon: '🍗', is_active: true, category_type: 'food' },
  { id: 'cat-fastfood', name: 'Fast Food', icon: '🍟', is_active: true, category_type: 'food' },
  { id: 'cat-pasta', name: 'Pasta', icon: '🍝', is_active: true, category_type: 'food' },
  { id: 'cat-breakfast', name: 'Breakfast', icon: '🍳', is_active: true, category_type: 'food' },
  { id: 'cat-cakes', name: 'Cakes', icon: '🎂', is_active: true, category_type: 'food' },
  { id: 'cat-chinese', name: 'Chinese', icon: '🥢', is_active: true, category_type: 'food' },
  { id: 'cat-sweets', name: 'Sweets & Curd', icon: '🍩', is_active: true, category_type: 'food' },
  { id: 'cat-dessert', name: 'Dessert', icon: '🍰', is_active: true, category_type: 'food' },
  { id: 'cat-bengali', name: 'Bengali', icon: '🐟', is_active: true, category_type: 'food' },
  { id: 'cat-salad', name: 'Salad', icon: '🥗', is_active: true, category_type: 'food' },
  { id: 'cat-kebab', name: 'Kebab', icon: '🍢', is_active: true, category_type: 'food' },
  { id: 'cat-thai', name: 'Thai', icon: '🍜', is_active: true, category_type: 'food' },
  { id: 'cat-icecream', name: 'Ice Cream', icon: '🍦', is_active: true, category_type: 'food' },
  { id: 'cat-pastry', name: 'Cake & Pastry', icon: '🧁', is_active: true, category_type: 'food' },
  { id: 'cat-rice', name: 'Rice', icon: '🍚', is_active: true, category_type: 'food' },
  { id: 'cat-soup', name: 'Soup', icon: '🥣', is_active: true, category_type: 'food' },
  { id: 'cat-juice', name: 'Juice', icon: '🍹', is_active: true, category_type: 'food' },
  { id: 'cat-coffee', name: 'Coffee & Tea', icon: '☕', is_active: true, category_type: 'food' },
  { id: 'cat-shawarma', name: 'Shawarma', icon: '🌯', is_active: true, category_type: 'food' },
  { id: 'cat-continental', name: 'Continental', icon: '🍽️', is_active: true, category_type: 'food' },
  { id: 'cat-bakery', name: 'Bakery', icon: '🥐', is_active: true, category_type: 'food' },
  { id: 'cat-beverage', name: 'Beverage', icon: '🥤', is_active: true, category_type: 'food' },
  { id: 'cat-seafood', name: 'Sea Food', icon: '🍤', is_active: true, category_type: 'food' },
  { id: 'cat-fish', name: 'Fish', icon: '🐟', is_active: true, category_type: 'food' },
  { id: 'cat-american', name: 'American', icon: '🌭', is_active: true, category_type: 'food' },
  { id: 'cat-indian', name: 'Indian', icon: '🫓', is_active: true, category_type: 'food' },
  { id: 'cat-japanese', name: 'Japanese', icon: '🍣', is_active: true, category_type: 'food' },
  { id: 'cat-turkish', name: 'Turkish', icon: '🥙', is_active: true, category_type: 'food' },
  { id: 'cat-arabian', name: 'Arabian', icon: '🥩', is_active: true, category_type: 'food' },
  { id: 'cat-steak', name: 'Steak', icon: '🥩', is_active: true, category_type: 'food' },
  { id: 'cat-asian', name: 'Asian', icon: '🥡', is_active: true, category_type: 'food' },
  { id: 'cat-mexican', name: 'Mexican', icon: '🌮', is_active: true, category_type: 'food' },
  { id: 'cat-spanish', name: 'Spanish', icon: '🥘', is_active: true, category_type: 'food' },
  { id: 'cat-italian', name: 'Italian', icon: '🍝', is_active: true, category_type: 'food' },
  { id: 'cat-korean', name: 'Korean', icon: '🍲', is_active: true, category_type: 'food' },
  { id: 'cat-western', name: 'Western', icon: '🍖', is_active: true, category_type: 'food' },
  { id: 'cat-bubbletea', name: 'Bubble Tea', icon: '🧋', is_active: true, category_type: 'food' },
  { id: 'cat-snacks', name: 'Snacks', icon: '🍿', is_active: true, category_type: 'food' },
  { id: 'cat-pickle', name: 'Pickle', icon: '🫙', is_active: true, category_type: 'food' },
  { id: 'cat-dips', name: 'Dips', icon: '🥣', is_active: true, category_type: 'food' },
  { id: 'cat-healthy', name: 'Healthy', icon: '🍎', is_active: true, category_type: 'food' },
  { id: 'cat-rolls', name: 'Rolls & Wrap', icon: '🌯', is_active: true, category_type: 'food' },
  { id: 'cat-coconut', name: 'Coconut', icon: '🥥', is_active: true, category_type: 'food' },
  { id: 'cat-ramadan', name: 'Ramadan', icon: '🌙', is_active: true, category_type: 'food' }
];
